// Sufijos de identidad para fichas de Sincopa que comparten artista y título con
// otro disco distinto del mismo artista («Grupo Mango::Mango» de 1975 y de 1976).
// Sin ellos la promoción los funde en un disco. Lo genera
// scripts/split-sincopa-mixed-albums.ts --write-overrides (decisión de Brian, 2026-10-03).
export const SINCOPA_IDENTITY_SUFFIX: Readonly<Record<string, string>> = {
  "https://sincopa.com/classic/cdinfo_class/aliriodiaz_74recital.htm": "1974",
  "https://sincopa.com/ethnic/cdinfo1/raices_1982.htm": "1982",
  "https://sincopa.com/ethnic/cdinfo1/raices_1983.htm": "1983",
  "https://sincopa.com/ethnic/cdinfo1/raices_1984.htm": "1984",
  "https://sincopa.com/latin_pop/cdinfo_latin/antonietta/antonietta_88antonietta.htm": "1988",
  "https://sincopa.com/latin_pop/cdinfo_latin/canelita_medina/canelita_82canelita.htm": "1982",
  "https://sincopa.com/latin_pop/cdinfo_latin/dimension_latina/dimensionlatina_15dimensionlatina.htm": "1980",
  "https://sincopa.com/latin_pop/cdinfo_latin/dimension_latina/dimensionlatina_23dimensionlatina.htm": "1987",
  "https://sincopa.com/latin_pop/cdinfo_latin/guaco/guaco_1991.htm": "1991",
  "https://sincopa.com/latin_pop/cdinfo_latin/jose_luis_rodriguez/joseluis_elidolo82.htm": "1982",
  "https://sincopa.com/latin_pop/cdinfo_latin/jose_luis_rodriguez/joseluis_lomejord_80.htm": "1980",
  "https://sincopa.com/latin_pop/cdinfo_latin/jose_luis_rodriguez/joseluis_lomejord_86.htm": "1986",
  "https://sincopa.com/latin_pop/cdinfo_latin/la5tagalaxia_1984.htm": "1984",
  "https://sincopa.com/latin_pop/cdinfo_latin/los_blanco/losblanco_15losblanco.htm": "1976",
  "https://sincopa.com/latin_pop/cdinfo_latin/mango/mango_1975.htm": "1975",
  "https://sincopa.com/latin_pop/cdinfo_latin/mango/mango_1979.htm": "1979",
  "https://sincopa.com/latin_pop/cdinfo_latin/mango/mango_1981.htm": "1981",
  "https://sincopa.com/latin_pop/cdinfo_latin/mango/mango_1983.htm": "1983",
  "https://sincopa.com/latin_pop/cdinfo_latin/mayra_marti/mayramarti_83mayramarti.htm": "1983",
  "https://sincopa.com/latin_pop/cdinfo_latin/mirla_castellanos/mirla_74mirla.htm": "1974",
  "https://sincopa.com/latin_pop/cdinfo_latin/nancy_ramos/nancyramos_85nancyramos.htm": "1985",
  "https://sincopa.com/latin_pop/cdinfo_latin/pinacolada_2palms85.htm": "1985",
  "https://sincopa.com/latin_pop/cdinfo_latin/punto_sur/puntosur_83puntosur.htm": "1983",
  "https://sincopa.com/latin_pop/cdinfo_latin/sexteto_juventud/6ttojuventud_brujeria_cd.htm": "2001",
  "https://sincopa.com/latin_pop/cdinfo_latin/sexteto_juventud/6ttojuventud_cocinandosalsa_cd.htm": "1996",
  "https://sincopa.com/latin_pop/cdinfo_latin/sonero_clasico_del_caribe/soneroclasico_80soneroclasico.htm": "1980",
  "https://sincopa.com/latin_pop/cdinfo_latin/sonero_clasico_del_caribe/soneroclasico_85soneroclasico.htm": "1985",
  "https://sincopa.com/latin_pop/cdinfo_latin/sonero_clasico_del_caribe/soneroclasico_97soneroclasico_cd1.htm": "1997",
  "https://sincopa.com/latin_pop/cdinfo_latin/trio_venezuela/triovzla_08triovzla62.htm": "1962",
  "https://sincopa.com/rock_pop/cdinfo_rock/ambar_1lovemaniac.htm": "ambar_1lovemaniac",
  "https://sincopa.com/rock_pop/cdinfo_rock/antbellobluesband_2bumblebee.htm": "antbellobluesband_2bumblebee",
  "https://sincopa.com/rock_pop/cdinfo_rock/banana_voladora2.htm": "1997",
  "https://sincopa.com/rock_pop/cdinfo_rock/carlosbaute_13historiasvol2.htm": "carlosbaute_13historiasvol2",
  "https://sincopa.com/rock_pop/cdinfo_rock/compilations1/2020_20exitos2_6070.htm": "2020_20exitos2_6070",
  "https://sincopa.com/rock_pop/cdinfo_rock/compilations1/lomaximo_16exitosd60_70.htm": "lomaximo_16exitosd60_70",
  "https://sincopa.com/rock_pop/cdinfo_rock/francodvita_grandesexitos.htm": "2014",
  "https://sincopa.com/rock_pop/cdinfo_rock/gcarrasco_2gc_polyd.htm": "1981",
  "https://sincopa.com/rock_pop/cdinfo_rock/germanfreytes2_6276.htm": "1969",
  "https://sincopa.com/rock_pop/cdinfo_rock/gina_agny3.htm": "1984",
  "https://sincopa.com/rock_pop/cdinfo_rock/grupobota_1975.htm": "1975",
  "https://sincopa.com/rock_pop/cdinfo_rock/grupobota_1976.htm": "1976",
  "https://sincopa.com/rock_pop/cdinfo_rock/grupobota_1977.htm": "1977",
  "https://sincopa.com/rock_pop/cdinfo_rock/impala_05sumusica.htm": "impala_05sumusica",
  "https://sincopa.com/rock_pop/cdinfo_rock/impala_06europa2.htm": "1968",
  "https://sincopa.com/rock_pop/cdinfo_rock/impala_09_1996.htm": "1996",
  "https://sincopa.com/rock_pop/cdinfo_rock/ivo_3ivo.htm": "1978",
  "https://sincopa.com/rock_pop/cdinfo_rock/los_cazadores_71thehunters.htm": "los_cazadores_71thehunters",
  "https://sincopa.com/rock_pop/cdinfo_rock/los_cazadores_88loscazadores.htm": "1988",
  "https://sincopa.com/rock_pop/cdinfo_rock/melissa_6melissa.htm": "1990",
  "https://sincopa.com/rock_pop/cdinfo_rock/rhapsodia_2.htm": "1987",
  "https://sincopa.com/traditional/cdinfo2/1solo_pueblo/1solopueblo_1992_vusp.htm": "1992",
  "https://sincopa.com/traditional/cdinfo2/grupo_vera/grupovera_84grupovera.htm": "1984",
  "https://sincopa.com/traditional/cdinfo2/gual_ibarreto_gualbertoibarreto.htm": "1984",
  "https://sincopa.com/traditional/cdinfo2/jv_torrealba/jvt_torrealberos501.htm": "jvt_torrealberos501",
  "https://sincopa.com/traditional/cdinfo2/jv_torrealba/jvt_torrealberos502.htm": "jvt_torrealberos502",
  "https://sincopa.com/traditional/cdinfo2/jv_torrealba/jvt_torrealberos503.htm": "jvt_torrealberos503",
  "https://sincopa.com/traditional/cdinfo2/jv_torrealba/jvt_torrealberos504.htm": "jvt_torrealberos504",
  "https://sincopa.com/traditional/cdinfo2/jv_torrealba/jvt_torrealberos505.htm": "jvt_torrealberos505",
  "https://sincopa.com/traditional/cdinfo2/simondiaz_carachanegro.htm": "1997",
  "https://sincopa.com/traditional/cdinfo2/simondiaz_tonadasyllanerias.htm": "1979",
};
