# Decisiones disco por disco (repertorio + título); ver discos-zona-gris.json.
import json
S="same:revision-ingesta-repertorio"; E="same:revision-ingesta-edicion"; T="same:revision-ingesta-titulo"; N="different:revision-ingesta-otro-disco"
d={
"María Rivas::Café Negrito (World-Latin)":(T,5558),
"María Rivas::Aquador (Chill-Out)":(T,5554),
"Rigel Mitxelena::Bártok's Room":(T,483),
"Rigel Mitxelena::Bartók's Room":(S,483),
"Virgilio Araque Reyes::Virgilio Araque En Concierto":(T,2373),
"Rigel Mitxelena::Música De Película":(T,15283),
"Rigel Mitxelena::Volumen 1 Junta Parroquial":(T,15285),
"Orquesta Sinfónica Venezuela (OSV)::Concierto De Las Tres Esferas":(T,5980),
"Orquesta Sinfónica Gran Mariscal de Ayacucho::Danzón - Música de Latinoamerica":(T,5921),
"Daiquiri::La Historia Lo Mejor del Chamo Candela":(T,6919),
"Cecilia Todd::Romanciando":(T,9155),
"Cecilia Todd::Pajarillo Verde (CD Reissue)":(E,5540),
"Simón Díaz::Simón En Gaita - En Salsa":(T,14620),
"Simón Díaz::Las Gaitas De Simón":(N,None),
"Simón Díaz::Golpe y Pasaje / Caballo Viejo":(T,14608),
"Simón Díaz::Cuenta y Canta Vol. 2":(N,None),
"Simón Díaz::Muy Venezolano Vol.2 (La Rondalla Vzlana)":(T,15276),
"Simón Díaz::Muy Venezolano Vol.3 (La Rondalla Vzlana)":(T,15330),
"Simón Díaz::Muy Venezolano Vol.4 (La Rondalla Vzlana)":(T,15348),
"Simón Díaz::Caracha Negro CD":(E,15376),
"Simón Díaz::Muy Venezolano Vol.5 (La Rondalla Vzlana)":(N,None),
"Simón Díaz::Muy Venezolano Vol.6 (La Rondalla Vzlana)":(N,None),
"Simón Díaz::Mis Tonadas 16 Grandes Exitos (Lo Máximo)":(T,15275),
"Cecilia Todd::Ni Na, Ni Na":(T,5539),
"Simón Díaz::Muy Venezolano Vol. 1":(T,15266),
"Simón Díaz::Las Gaitas De Simón Enemigo Publico Nº1":(T,15256),
"Simón Díaz::Tonada y Pasaje La Yegua Blanca":(T,15260),
"Simón Díaz::32 Grandes Exitos":(T,15267),
"Simón Díaz::Serie Lo Máximo Simón Díaz 16 Grandes Exitos":(T,15275),
"Simón Díaz::Serie Lo Máximo Simón Díaz-Mis Tonadas 16 Grandes Exitos":(S,14629),
"C4 Trío::C4 Trío y Desorden Público - Pa' Fuera":(T,15448),
"C4 Trío::C4 Trío y Luis Enrique - Tiempo al Tiempo":(T,15713),
"Gaélica::Paz: Una Navidad Celta En Venezuela":(N,None),
"Ad Intra::The Attic (EP)":(T,1819),
"Ad Intra::We Aren't Ready To Take Off (EP)":(T,3634),
"Aditus::Juegos del Azar":(T,3014),
"Agni Mogollón::Gina y Agny":(N,None),
"Agresión::Silent Smile (EP)":(T,3392),
"Gillman::Levántate y Pelea 40 Aniversario":(T,4150),
"Henry Stephen::Mi Limon, Mi Limonero 40 Años 40 Exitos":(S,4216),
"Los Mentas::U.E.L.M. \"Unidad Educativa Los Mentas\"":(S,600),
"Témpano::El Fin De La Infancia / Childhood's End":(S,362),
"Karina::14 Exitos de Karina Serie Lo Máximo":(S,4332),
"Rudy La Scala::16 Grandes Exitos / Serie Lo Máximo":(S,3655),
"Los Pixel::Cuánto Cuesta":(S,606),
"Karina::32 Grandes Exitos Serie 32":(S,4324),
"Kiara::Exitos - The Universal Masters Collection":(S,4345),
"Gillman::Tributo A Los Desconocidos":(S,4148),
"Gillman::Cuauhtemoc":(S,2125),
"Jorge Aguilar::Aguilar (Spanish Version)":(N,None),
"Neblina::Una Canción De Navidad":(S,3597),
"Gillman::Tesoros 40 Aniversario":(E,4141),
"Gillman::Presente":(S,4143),
"Gusanos::Días De Furia":(S,255),
"Gillman::Inevitable":(S,2139),
"Grupo C::Grupo C Canta Edgar Castro":(S,2697),
"Gillman::El Guerrero":(S,2150),
"Gillman::Levántate y Pelea":(S,2152),
"Los Mentas::Arriba Carajo 15 Años En Vivo":(T,2273),
"Gillman::Escalofrío":(S,450),
"Various Artists::Rock":(N,None),
"Various Artists::Serie Lo Máximo 19 Exitos de Donde Son Los Cantantes Vol. 2":(N,None),
"Aditus::Lo Mejor de Aditus Colección del Milenio":(S,3642),
"Aditus::25 Aniversario Y La Historia Continúa Serie 32":(S,2134),
"Aditus::Ni En Concierto Ni En Estudio Sino Todo Lo Contrario":(S,3643),
"Caramelos de Cianuro::Flor De Fuego (Special Edition)":(E,140),
"Distrust::Behold The Zombie Nation":(S,1741),
"Spiteri::Spiteri":(S,51),
# Artista truncado por el HTML de Sincopa («Oscar», «Grupo»): fichas ya creadas en el core.
"Oscar::Cuidao Con Los Escalones":(T,6428),
"Grupo::Grupo Taburete":(T,8585),
"Grupo::Grupo Raíces":(T,9560),
"Grupo::Raices":(T,9561),
}
out={}
for k,(v,t) in d.items():
  kind,rule=v.split(":")
  out[k]={"kind":kind,"rule":rule,**({"targetId":t} if t else {})}
json.dump(out,open("reports/revision-ingesta-2026-10-04/overrides-discos.json","w"),ensure_ascii=False,indent=1)
print(len(out))
